baseurl: "https://sandcastle.io/"
languageCode: "en-au"
title: "Sandcastle"
theme: "sandcastle"
canonifyurls: true
metaDataFormat: "yaml"

author:
  name: "Glenn Morton"

permalinks:
  posts: /blog/:slug/

params:
  copyright: "&copy; 1999 Glenn Morton"
  github: "sandcastle"
