#!/bin/sh

# script/publish - publishes the site

cd "$(dirname "$0")/.."

# ------

sh script/build

# ------

echo "Publishing ..."
cd public

git checkout master
git add -A
git commit -m "Publishing `date +"%F"`"
git push origin master

cd ..
echo "Publish complete!"

# ------

echo "Saving content ..."

message="${1:-"Content `date +"%F"`"}"

git add -A
git commit -m "${message}"
git pull --rebase
git push

echo "Saving content complete!"

# ------
