#!/bin/sh
set -e

# script/setup - sets up the site

cd "$(dirname "$0")/.."

# ------

git checkout source

rm -rf public
git subtree add --prefix=public git@github.com:sandcastle/sandcastle.github.io.git master --squash

git subtree pull --prefix=public git@github.com:sandcastle/sandcastle.github.io.git master

# ------

sh script/build

# ------
