name = "sandcastle"
license = "MIT"
description = "A basic styling theme based off the base16 theme from htdvisser"
homepage = "https://github.com/sandcastle/sandcastle.github.io/themes/sandcastle"
tags = ["blog", "syntax highlighting"]
features = ["blog", "syntax highlighting"]
min_version = 0.14

[author]
name = "Glenn Morton"
homepage = "https://sandcastle.io/"
